
QUESTS = {
    "animalmag": {
        "name": "Animal Magnetism",
        "description": "Assist Ava in Draynor Manor to create a device that attracts items to you.",
        "quests": ["cooks", "priestperil", "ernestchicken"],
        "skills": {"slayer": 18, "crafting": 19, "ranged": 30, "woodcutting": 35},
        "skills_recommended": {"prayer": 43},
        "xp_rewards": {},  # No direct XP rewards
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 1,
        "quest_points_reward": 1
    },
    "cooks": {
        "name": "Cook's Assistant",
        "description": "Help the Lumbridge cook bake a cake.",
        "quests": [],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"cooking": 300},
        "members": False,
        "difficulty": "Novice",
        "length": "Very Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "treegnome": {
        "name": "Tree Gnome Village",
        "description": "Help the gnomes reclaim their home from General Khazard.",
        "quests": ["cooks"],
        "skills": {"agility": 15, "attack": 40},
        "skills_recommended": {"combat": 40},
        "xp_rewards": {"agility": 1000, "attack": 2000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "priestperil": {
        "name": "Priest in Peril",
        "description": "Help King Roald secure the temple of Saradomin from dark forces.",
        "quests": [],
        "skills": {},
        "skills_recommended": {"combat": 25},
        "xp_rewards": {"prayer": 1406},
        "members": True,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "shadowstorm": {
        "name": "Shadow Storm",
        "description": "Aid a powerful mage in overcoming a demonic force.",
        "quests": ["demonslayer", "priestperil"],
        "skills": {"ranged": 30},
        "skills_recommended": {"magic": 40},
        "xp_rewards": {"magic": 10000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 5,
        "quest_points_reward": 2
    },
    "biohazard": {
        "name": "Biohazard",
        "description": "Expose the truth about the Plague in Ardougne.",
        "quests": ["plaguecity"],
        "skills": {},
        "skills_recommended": {"thieving": 25},
        "xp_rewards": {},
        "members": True,
        "difficulty": "Novice",
        "length": "Medium",
        "quest_points_required": 1,
        "quest_points_reward": 3
    },
    "bigchompybirdhunting": {
        "name": "Big Chompy Bird Hunting",
        "description": "Learn how to hunt and cook Chompy birds.",
        "quests": [],
        "skills": {"cooking": 30, "ranged": 30, "fletching": 5},
        "skills_recommended": {"combat": 40},
        "xp_rewards": {},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "deathplateau": {
        "name": "Death Plateau",
        "description": "Help the Burthorpe guards establish a new route to Death Plateau.",
        "quests": [],
        "skills": {},
        "skills_recommended": {"combat": 20},
        "xp_rewards": {"attack": 3000},
        "members": True,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "druidicritual": {
        "name": "Druidic Ritual",
        "description": "Join the druids and learn the art of Herblore.",
        "quests": [],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"herblore": 250},
        "members": True,
        "difficulty": "Novice",
        "length": "Very Short",
        "quest_points_required": 0,
        "quest_points_reward": 4
    },
    "runemysteries": {
        "name": "Rune Mysteries",
        "description": "Learn about the secrets of Runecrafting.",
        "quests": [],
        "skills": {},
        "skills_recommended": {"magic": 10},
        "xp_rewards": {"runecraft": 1400},
        "members": False,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "deserttreasureone": {
        "name": "Desert Treasure I",
        "description": "Embark on a perilous journey to uncover ancient magical artifacts.",
        "quests": ["digsite", "priestperil", "templeikov", "trollstronghold"],
        "skills": {"magic": 50},
        "skills_recommended": {"combat": 70, "prayer": 43},
        "xp_rewards": {"magic": 20000},
        "members": True,
        "difficulty": "Master",
        "length": "Long",
        "quest_points_required": 10,
        "quest_points_reward": 3
    },
	"fightarena": {
		"name": "Fight Arena",
		"description": "Help a gnome rescue his family from General Khazard's clutches.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"combat": 30},
		"xp_rewards": {"attack": 12175, "thieving": 2000},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"fishcontest": {
		"name": "Fishing Contest",
		"description": "Win a fishing contest to help the Mountain Dwarves.",
		"quests": ["dwarfcannon"],
		"skills": {},
		"skills_recommended": {"fishing": 10},
		"xp_rewards": {"fishing": 2437},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"fremmytrials": {
		"name": "The Fremennik Trials",
		"description": "Prove your worth to join the Fremennik clan.",
		"quests": [],
		"skills": {"agility": 40, "woodcutting": 40, "crafting": 25, "fletching": 25},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {"strength": 2800, "defence": 2800, "attack": 2800, "constitution": 2800},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Long",
		"quest_points_required": 0,
		"quest_points_reward": 3
	},
	"gertrudes": {
		"name": "Gertrude's Cat",
		"description": "Help Gertrude find her lost cat.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"cooking": 1500},
		"members": False,
		"difficulty": "Novice",
		"length": "Very Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"ghostsahoy": {
		"name": "Ghosts Ahoy",
		"description": "Help the ghosts of Port Phasmatys and earn your Ectophial.",
		"quests": ["priestperil"],
		"skills": {"prayer": 25},
		"skills_recommended": {"crafting": 20},
		"xp_rewards": {"prayer": 2400},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 1,
		"quest_points_reward": 2
	},
	"goblindip": {
		"name": "Goblin Diplomacy",
		"description": "Settle a dispute between goblins over armor color.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": False,
		"difficulty": "Novice",
		"length": "Very Short",
		"quest_points_required": 0,
		"quest_points_reward": 5
	},
	"grandtree": {
		"name": "The Grand Tree",
		"description": "Help the King of the Gnomes uncover a conspiracy.",
		"quests": ["treegnome"],
		"skills": {"agility": 25},
		"skills_recommended": {"combat": 45},
		"xp_rewards": {"agility": 18000, "magic": 2150},
		"members": True,
		"difficulty": "Experienced",
		"length": "Long",
		"quest_points_required": 5,
		"quest_points_reward": 5
	},
	"hazeelcult": {
		"name": "Hazeel Cult",
		"description": "Help or hinder a cult trying to revive Hazeel.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"combat": 15},
		"xp_rewards": {"thieving": 2000},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"holygrail": {
		"name": "Holy Grail",
		"description": "Find the Holy Grail to help King Arthur.",
		"quests": ["merlincrystal"],
		"skills": {},
		"skills_recommended": {"prayer": 31},
		"xp_rewards": {"prayer": 11000, "defence": 15300},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Long",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"horror": {
		"name": "Horror from the Deep",
		"description": "Investigate the lighthouse and uncover a terrifying creature.",
		"quests": [],
		"skills": {"crafting": 30},
		"skills_recommended": {"combat": 50},
		"xp_rewards": {"crafting": 4662, "magic": 4662},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"impcatcher": {
		"name": "Imp Catcher",
		"description": "Retrieve magical beads from imps for the Wizard Mizgog.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"magic": 10},
		"xp_rewards": {"magic": 875},
		"members": False,
		"difficulty": "Novice",
		"length": "Very Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"knightssword": {
		"name": "The Knight's Sword",
		"description": "Help a squire recover his master's sword.",
		"quests": [],
		"skills": {"mining": 10},
		"skills_recommended": {},
		"xp_rewards": {"smithing": 12725},
		"members": False,
		"difficulty": "Novice",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"lostcity": {
		"name": "Lost City",
		"description": "Uncover the entrance to Zanaris and wield Dragon weapons.",
		"quests": [],
		"skills": {"crafting": 31, "woodcutting": 36},
		"skills_recommended": {"combat": 50},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 3
	},
	"losttribe": {
		"name": "The Lost Tribe",
		"description": "Uncover the mystery behind the Dorgeshuun goblins.",
		"quests": ["goblindip"],
		"skills": {},
		"skills_recommended": {"mining": 15},
		"xp_rewards": {"mining": 3000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"makinghistory": {
		"name": "Making History",
		"description": "Help the outpost commander uncover ancient relics.",
		"quests": ["priestperil"],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"crafting": 1000, "prayer": 1000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 1,
		"quest_points_reward": 3
	},
	"merlincrystal": {
		"name": "Merlin's Crystal",
		"description": "Free Merlin from his crystal prison.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"combat": 30},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 6
	},
	"monkeymadness": {
		"name": "Monkey Madness I",
		"description": "Help the 10th Squad and unlock the secrets of Ape Atoll.",
		"quests": ["grandtree", "treegnome"],
		"skills": {"agility": 40},
		"skills_recommended": {"combat": 70, "prayer": 43},
		"xp_rewards": {"attack": 35000, "strength": 35000, "defence": 35000},
		"members": True,
		"difficulty": "Master",
		"length": "Very Long",
		"quest_points_required": 5,
		"quest_points_reward": 3
	},
	"monksfriend": {
		"name": "Monk's Friend",
		"description": "Help the monks of Ardougne retrieve their stolen items.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"woodcutting": 2000},
		"members": True,
		"difficulty": "Novice",
		"length": "Very Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"mountaindaughter": {
		"name": "Mountain Daughter",
		"description": "Help the Mountain Camp resolve their spiritual troubles.",
		"quests": [],
		"skills": {"agility": 20},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {"attack": 1000, "prayer": 2000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"murdermystery": {
		"name": "Murder Mystery",
		"description": "Solve the Sinclair family's murder case.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"crafting": 10},
		"xp_rewards": {"crafting": 1406},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 3
	},
	"naturespirit": {
		"name": "Nature Spirit",
		"description": "Help the nature spirit purify Mort Myre.",
		"quests": ["priestperil"],
		"skills": {"crafting": 18},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {"crafting": 2000, "defence": 2000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"observatory": {
		"name": "Observatory Quest",
		"description": "Help the Observatory Professor repair his telescope.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"crafting": 10},
		"xp_rewards": {"crafting": 1250},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"onesmallfavour": {
		"name": "One Small Favour",
		"description": "Complete a series of tasks to help Gielinor's residents.",
		"quests": ["shilovillage"],
		"skills": {"agility": 36},
		"skills_recommended": {"combat": 50},
		"xp_rewards": {"herblore": 2000, "crafting": 2000},
		"members": True,
		"difficulty": "Experienced",
		"length": "Very Long",
		"quest_points_required": 3,
		"quest_points_reward": 2
	},
	"plaguecity": {
		"name": "Plague City",
		"description": "Help uncover the secrets of the West Ardougne plague.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"mining": 15},
		"xp_rewards": {"mining": 2425},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"porcineofinterest": {
		"name": "A Porcine of Interest",
		"description": "Investigate the source of strange noises in Draynor.",
		"quests": [],
		"skills": {"slayer": 10},
		"skills_recommended": {},
		"xp_rewards": {"slayer": 1000},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"queenthieves": {
		"name": "The Queen of Thieves",
		"description": "Assist a rebellion in Kourend.",
		"quests": [],
		"skills": {"thieving": 32},
		"skills_recommended": {},
		"xp_rewards": {"thieving": 2000},
		"members": True,
		"difficulty": "Novice",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"recruitmentdrive": {
		"name": "Recruitment Drive",
		"description": "Help Sir Tiffy recruit for the Temple Knights.",
		"quests": ["blackknightfortress"],
		"skills": {"herblore": 10},
		"skills_recommended": {"prayer": 25},
		"xp_rewards": {"prayer": 1000, "herblore": 1000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"restlessghost": {
		"name": "The Restless Ghost",
		"description": "Help a ghost in Lumbridge find peace.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"prayer": 1125},
		"members": False,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"rfdgoblin": {
		"name": "Recipe for Disaster: Goblin Generals",
		"description": "Help the goblin generals in the Lumbridge kitchen.",
		"quests": ["rfdstart"],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"cooking": 1000},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"romeojuliet": {
		"name": "Romeo & Juliet",
		"description": "Help Romeo find his true love.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": False,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 5
	},
	"scorpioncatcher": {
		"name": "Scorpion Catcher",
		"description": "Recover the three lost scorpions for Thormac the Seer.",
		"quests": [],
		"skills": {"prayer": 31},
		"skills_recommended": {"combat": 50},
		"xp_rewards": {"strength": 6625},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"seaslug": {
		"name": "Sea Slug",
		"description": "Investigate missing villagers on the Fishing Platform.",
		"quests": [],
		"skills": {"fishing": 30},
		"skills_recommended": {"combat": 20},
		"xp_rewards": {"fishing": 7175},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"shilovillage": {
		"name": "Shilo Village",
		"description": "Explore the secrets of Shilo Village.",
		"quests": [],
		"skills": {"crafting": 20},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {"crafting": 3875},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Long",
		"quest_points_required": 3,
		"quest_points_reward": 2
	},
	"sleepinggiants": {
		"name": "Sleeping Giants",
		"description": "Assist Kovac with his anvil project.",
		"quests": [],
		"skills": {"smithing": 15},
		"skills_recommended": {"combat": 30},
		"xp_rewards": {"smithing": 5000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"taibaitrio": {
		"name": "Tai Bwo Wannai Trio",
		"description": "Help the villagers of Tai Bwo Wannai with their challenges.",
		"quests": ["junglepotion"],
		"skills": {"cooking": 30, "fishing": 5},
		"skills_recommended": {"combat": 35},
		"xp_rewards": {"cooking": 2000, "fishing": 2000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"tribaltotem": {
		"name": "Tribal Totem",
		"description": "Recover a stolen totem for a villager in Brimhaven.",
		"quests": [],
		"skills": {"thieving": 21},
		"skills_recommended": {},
		"xp_rewards": {"thieving": 1775},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"trollromance": {
		"name": "Troll Romance",
		"description": "Help a troll win the heart of his beloved.",
		"quests": ["deathplateau"],
		"skills": {"agility": 28},
		"skills_recommended": {"combat": 50},
		"xp_rewards": {"agility": 8000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 1,
		"quest_points_reward": 2
	},
	"ugpass": {
		"name": "Underground Pass",
		"description": "Navigate the treacherous underground pass.",
		"quests": ["deathplateau"],
		"skills": {},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Long",
		"quest_points_required": 1,
		"quest_points_reward": 2
	},
	"vampireslayer": {
		"name": "Vampire Slayer",
		"description": "Defeat the vampire terrorizing Draynor Village.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"combat": 20},
		"xp_rewards": {"attack": 4825},
		"members": False,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 3
	},
	"varrockmuseum": {
		"name": "Varrock Museum Cleanup",
		"description": "Help the Varrock Museum staff restore their exhibits.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"crafting": 5, "mining": 10},
		"xp_rewards": {"hunter": 1000, "slayer": 1000},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"wanted": {
		"name": "Wanted!",
		"description": "Track down a fugitive for the Temple Knights.",
		"quests": ["recruitmentdrive"],
		"skills": {"slayer": 14},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {"slayer": 5000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 1,
		"quest_points_reward": 1
	},
	"waterfall": {
		"name": "Waterfall Quest",
		"description": "Explore the secrets of the Baxtorian Falls.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"combat": 30},
		"xp_rewards": {"attack": 13750, "strength": 13750},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"witchshouse": {
		"name": "Witch's House",
		"description": "Retrieve a lost ball from a witch's garden.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"combat": 10},
		"xp_rewards": {"hitpoints": 6325},
		"members": False,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 4
	},
	"witchspotion": {
		"name": "Witch's Potion",
		"description": "Help a witch brew a magical potion.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"magic": 325},
		"members": False,
		"difficulty": "Novice",
		"length": "Very Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"xmarks": {
		"name": "X Marks the Spot",
		"description": "Solve a treasure hunt around Lumbridge.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"coins": 2000},
		"members": False,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"zogreflesheaters": {
		"name": "Zogre Flesh Eaters",
		"description": "Investigate strange happenings in the Zogre burial site.",
		"quests": ["bigchompybirdhunting"],
		"skills": {"ranged": 30},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {"strength": 2000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 1,
		"quest_points_reward": 2
	},
	"darknesshallowvale": {
		"name": "Darkness of Hallowvale",
		"description": "Assist the Myreque in their rebellion against the vampires.",
		"quests": ["aidmyreque"],
		"skills": {"agility": 50},
		"skills_recommended": {"combat": 60},
		"xp_rewards": {"agility": 7000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Long",
		"quest_points_required": 7,
		"quest_points_reward": 2
	},
	"deserttreasureone": {
		"name": "Desert Treasure I",
		"description": "Seek out ancient magical artifacts across Gielinor.",
		"quests": ["digsite", "priestperil", "templeikov", "trollstronghold"],
		"skills": {"magic": 50},
		"skills_recommended": {"combat": 70, "prayer": 43},
		"xp_rewards": {"magic": 20000},
		"members": True,
		"difficulty": "Master",
		"length": "Very Long",
		"quest_points_required": 10,
		"quest_points_reward": 3
	},
	"barcrawl": {
		"name": "Alfred Grimhand's Barcrawl",
		"description": "Complete a barcrawl to gain entry to the Barbarian Outpost.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 0
	},
	"belowicemountain": {
		"name": "Below Ice Mountain",
		"description": "Explore an ancient dungeon beneath Ice Mountain.",
		"quests": [],
		"skills": {"mining": 16},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"blackknightfortress": {
		"name": "Black Knights' Fortress",
		"description": "Infiltrate the Black Knights' Fortress and foil their evil plans.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"combat": 20},
		"xp_rewards": {},
		"members": False,
		"difficulty": "Novice",
		"length": "Medium",
		"quest_points_required": 12,
		"quest_points_reward": 3
	},
	"bonevoyage": {
		"name": "Bone Voyage",
		"description": "Assist the Varrock Museum in uncovering the secrets of Fossil Island.",
		"quests": ["varrockmuseum"],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"clientkourend": {
		"name": "Client of Kourend",
		"description": "Help a mysterious client gather information about Kourend.",
		"quests": [],
		"skills": {},
		"skills_recommended": {"agility": 10},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Novice",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"creaturefenkenstrain": {
		"name": "Creature of Fenkenstrain",
		"description": "Assist Dr. Fenkenstrain in his spooky experiments.",
		"quests": ["priestperil"],
		"skills": {},
		"skills_recommended": {"crafting": 20},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"depthsdespair": {
		"name": "The Depths of Despair",
		"description": "Recover the Varlamore book for Lord Kandur Hosidius.",
		"quests": ["clientkourend"],
		"skills": {"agility": 18},
		"skills_recommended": {},
		"xp_rewards": {"agility": 1500},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"dorics": {
		"name": "Doric's Quest",
		"description": "Help Doric gather materials for his smithing project.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"mining": 1300},
		"members": False,
		"difficulty": "Novice",
		"length": "Very Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"dwarfcannon": {
		"name": "Dwarf Cannon",
		"description": "Help the dwarves repair their multicannon defense system.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"elemworkshopone": {
		"name": "Elemental Workshop I",
		"description": "Discover the secrets of the Elemental Workshop.",
		"quests": [],
		"skills": {"mining": 20},
		"skills_recommended": {},
		"xp_rewards": {"smithing": 5000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"enterabyss": {
		"name": "Enter the Abyss",
		"description": "Learn the art of Runecrafting through the Abyss.",
		"quests": ["runemysteries"],
		"skills": {},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {"runecraft": 1000},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 0
	},
	"ernestchicken": {
		"name": "Ernest the Chicken",
		"description": "Help Ernest escape from Draynor Manor.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": False,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 4
	},
	"itchyhelper": {
		"name": "Itchy Helper",
		"description": "Aid a witch doctor in performing a strange ritual.",
		"quests": ["druidicritual"],
		"skills": {"agility": 20, "thieving": 20, "woodcutting": 20},
		"skills_recommended": {"combat": 30},
		"xp_rewards": {"agility": 4000, "thieving": 4000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"junglepotion": {
		"name": "Jungle Potion",
		"description": "Help Trufitus find herbs for his potions.",
		"quests": [],
		"skills": {"herblore": 3},
		"skills_recommended": {"combat": 30},
		"xp_rewards": {"herblore": 775},
		"members": True,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
	"piratestreasure": {
		"name": "Pirate's Treasure",
		"description": "Find buried treasure for a pirate in Port Sarim.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": False,
		"difficulty": "Novice",
		"length": "Short",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"princealirescue": {
		"name": "Prince Ali Rescue",
		"description": "Rescue Prince Ali from Al Kharid.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {},
		"members": False,
		"difficulty": "Novice",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 3
	},
	"searchofmyreque": {
		"name": "In Search of the Myreque",
		"description": "Help the Myreque establish a foothold in Morytania.",
		"quests": ["naturespirit"],
		"skills": {"herblore": 25},
		"skills_recommended": {"combat": 40},
		"xp_rewards": {"attack": 3000, "herblore": 2000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"sheepshearer": {
		"name": "Sheep Shearer",
		"description": "Help Farmer Fred by shearing his sheep.",
		"quests": [],
		"skills": {},
		"skills_recommended": {},
		"xp_rewards": {"crafting": 150},
		"members": False,
		"difficulty": "Novice",
		"length": "Very Short",
		"quest_points_required": 0,
		"quest_points_reward": 1
	},
    "demonslayer": {
        "name": "Demon Slayer",
        "description": "Defeat the powerful demon Delrith to save Varrock.",
        "quests": [],
        "skills": {},
        "skills_recommended": {"combat": 10},
        "xp_rewards": {},
        "members": False,
        "difficulty": "Novice",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 3
    },
    "rfdstart": {
        "name": "Recipe for Disaster (Start)",
        "description": "Embark on an epic quest to save the Lumbridge banquet attendees.",
        "quests": ["cooks"],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {},
        "members": True,
        "difficulty": "Special",
        "length": "Very Long",
        "quest_points_required": 10,
        "quest_points_reward": 1
    },
    "tailoftwocats": {
        "name": "A Tail of Two Cats",
        "description": "Help Bob the Cat uncover his mysterious past.",
        "quests": ["itchyhelper"],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"agility": 2500},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "templeeye": {
        "name": "Temple of the Eye",
        "description": "Discover the secrets of the Guardians of the Rift.",
        "quests": ["priestperil"],
        "skills": {"runecraft": 27},
        "skills_recommended": {},
        "xp_rewards": {"runecraft": 5000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "thefeud": {
        "name": "The Feud",
        "description": "Resolve a feud between two rival families in Al Kharid.",
        "quests": [],
        "skills": {"thieving": 30},
        "skills_recommended": {},
        "xp_rewards": {"thieving": 15000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "thegolem": {
        "name": "The Golem",
        "description": "Uncover the secrets of an ancient golem in the desert.",
        "quests": [],
        "skills": {"crafting": 20},
        "skills_recommended": {},
        "xp_rewards": {"crafting": 2000},
        "members": True,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "touristtrap": {
        "name": "The Tourist Trap",
        "description": "Rescue two kidnapped tourists from the desert slave camp.",
        "quests": [],
        "skills": {"smithing": 10},
        "skills_recommended": {},
        "xp_rewards": {"agility": 4650},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "treegnomevillage": {
        "name": "Tree Gnome Village",
        "description": "Help the gnomes defend their stronghold against General Khazard.",
        "quests": [],
        "skills": {},
        "skills_recommended": {"combat": 40},
        "xp_rewards": {"attack": 11000},
        "members": True,
        "difficulty": "Novice",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "regicide": {
        "name": "Regicide",
        "description": "Assist King Lathas in a dangerous mission behind enemy lines.",
        "quests": ["ugpass"],
        "skills": {"agility": 56},
        "skills_recommended": {},
        "xp_rewards": {"agility": 13750},
        "members": True,
        "difficulty": "Master",
        "length": "Long",
        "quest_points_required": 25,
        "quest_points_reward": 3
    },
    "rovingelves": {
        "name": "Roving Elves",
        "description": "Help Islwyn and Ilfeen rebuild their strength.",
        "quests": ["regicide"],
        "skills": {"agility": 56},
        "skills_recommended": {},
        "xp_rewards": {"strength": 10000, "attack": 10000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "mepone": {
        "name": "Mourning's End Part I",
        "description": "Help Arianwyn uncover the secrets of the Temple of Light.",
        "quests": ["rovingelves"],
        "skills": {"agility": 56},
        "skills_recommended": {},
        "xp_rewards": {"agility": 25000},
        "members": True,
        "difficulty": "Master",
        "length": "Very Long",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "meptwo": {
        "name": "Mourning's End Part II",
        "description": "Complete the dangerous challenges in the Temple of Light.",
        "quests": ["mepone"],
        "skills": {"agility": 60},
        "skills_recommended": {},
        "xp_rewards": {"agility": 30000},
        "members": True,
        "difficulty": "Master",
        "length": "Very Long",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "aidmyreque": {
        "name": "In Aid of the Myreque",
        "description": "Assist the Myreque in fortifying their defenses in Burgh de Rott.",
        "quests": ["searchofmyreque"],
        "skills": {"crafting": 25},
        "skills_recommended": {},
        "xp_rewards": {"crafting": 2000, "attack": 2000, "defence": 2000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Long",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "tastehope": {
        "name": "A Taste of Hope",
        "description": "Assist the Myreque in striking back against the Vampyres.",
        "quests": ["aidmyreque"],
        "skills": {"agility": 30},
        "skills_recommended": {},
        "xp_rewards": {"agility": 2000, "strength": 2000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "templeikov": {
        "name": "Temple of Ikov",
        "description": "Recover the Staff of Armadyl from the Temple of Ikov.",
        "quests": ["priestperil"],
        "skills": {"ranged": 40},
        "skills_recommended": {},
        "xp_rewards": {"ranged": 8000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "enlightenedjourney": {
        "name": "Enlightened Journey",
        "description": "Assist the Entrana monks in creating a hot air balloon system.",
        "quests": ["clients_kourend"],
        "skills": {"firemaking": 20},
        "skills_recommended": {},
        "xp_rewards": {},
        "members": True,
        "difficulty": "Novice",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "watchtower": {
        "name": "Watchtower",
        "description": "Help the Yanille Watchtower Wizards secure their tower.",
        "quests": [],
        "skills": {"magic": 15},
        "skills_recommended": {},
        "xp_rewards": {"magic": 15000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 15,
        "quest_points_reward": 4
    },
    "rfddwarf": {
        "name": "Recipe for Disaster: The Dwarf",
        "description": "Assist the Dwarf in the Lumbridge banquet.",
        "quests": ["rfdstart"],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"cooking": 1000},
        "members": True,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "rfddave": {
        "name": "Recipe for Disaster: Evil Dave",
        "description": "Help Evil Dave in Edgeville Dungeon prepare his dish.",
        "quests": ["rfdstart"],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"cooking": 1000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "rfdguide": {
        "name": "Recipe for Disaster: Lumbridge Guide",
        "description": "Assist the Lumbridge Guide in the banquet.",
        "quests": ["rfdstart"],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"cooking": 1000},
        "members": True,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "rfdpete": {
        "name": "Recipe for Disaster: Pirate Pete",
        "description": "Help Pirate Pete prepare his banquet dish.",
        "quests": ["rfdstart"],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"cooking": 1000},
        "members": True,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "rfdskrach": {
        "name": "Recipe for Disaster: Skrach Uglogwee",
        "description": "Assist Skrach Uglogwee with his meal for the banquet.",
        "quests": ["rfdstart"],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"cooking": 1000},
        "members": True,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
    "rfdmonkey": {
        "name": "Recipe for Disaster: Monkey Ambassador",
        "description": "Assist the Monkey Ambassador with his banquet dish.",
        "quests": ["rfdstart", "monkeymadness"],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {"cooking": 1000},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 1
    },
	    "childrensun": {
        "name": "Children of the Sun",
        "description": "Aid the desert people in their quest for survival and uncover their ancient secrets.",
        "quests": [],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {},
        "members": True,
        "difficulty": "Intermediate",
        "length": "Medium",
        "quest_points_required": 0,
        "quest_points_reward": 2
    },
    "contact": {
        "name": "Contact!",
        "description": "Delve into the secrets of Sophanem and help the city guard fight back against a mysterious threat.",
        "quests": ["itchyhelper"],
        "skills": {"combat": 50},
        "skills_recommended": {"prayer": 43},
        "xp_rewards": {"slayer": 7000},
        "members": True,
        "difficulty": "Experienced",
        "length": "Medium",
        "quest_points_required": 1,
        "quest_points_reward": 1
    },
    "sheepherder": {
        "name": "Sheep Herder",
        "description": "Help the Ardougne authorities deal with a dangerous livestock problem.",
        "quests": [],
        "skills": {},
        "skills_recommended": {},
        "xp_rewards": {},
        "members": True,
        "difficulty": "Novice",
        "length": "Short",
        "quest_points_required": 0,
        "quest_points_reward": 4
    },
	"digsite": {
		"name": "The Dig Site",
		"description": "Help the Varrock Museum uncover ancient artifacts and learn about archaeology.",
		"quests": [],
		"skills": {"agility": 10, "herblore": 10, "thieving": 25},
		"skills_recommended": {},
		"xp_rewards": {"mining": 15300, "herblore": 2000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 0,
		"quest_points_reward": 2
	},
	"trollstronghold": {
		"name": "Troll Stronghold",
		"description": "Help the Imperial Guard defeat the trolls who have taken over the Stronghold.",
		"quests": ["deathplateau"],
		"skills": {"attack": 15},
		"skills_recommended": {"combat": 45, "prayer": 43},
		"xp_rewards": {"attack": 20000},
		"members": True,
		"difficulty": "Intermediate",
		"length": "Medium",
		"quest_points_required": 1,
		"quest_points_reward": 1
	}
}